FROM node:20.9.0-bookworm

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json ./ 

RUN npm install

ENV API="https://prodapiresttheliko.azurewebsites.net"

COPY . . 

RUN npm run build

EXPOSE 3000

ENTRYPOINT npm run start 